sudo: false
branches:
  only:
    - gh-pages
language: node_js
node_js:
  - stable
script:
  - npm install
  - npm run clean
  - npm run build:ng
cache:
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: nobackend.website
  region: ap-southeast-1
  skip_cleanup: true
  local_dir: _ng
  on:
    branch: gh-pages