permalink: /:year-:month-:day-:title
paginate: 10
markdown: kramdown
encoding: utf-8

author:
  name: 吕立青
  email: jimmy.jinglv@gmail.com
  link: http://blog.jimmylv.info
  github: http://github.com/JimmyLv
  weibo: http://weibo.com/liqing215
  zhihu: http://www.zhihu.com/people/JimmyLv

project:
  title: NoBackend Website
  subtitle: 最美博客
  description: A powerful rich interactive web application by using nobackend tech stack.
  repository: https://github.com/JimmyLv/nobackend.website
  website: http://nobackend.website

# github endpoint
github:
  user: JimmyLv
  repo: nobackend.website
  branch: gh-pages
  posts: _posts

# api endpoint
api:
  github:
    base: http://nobackend.website
    index: /api/index.json
    slides: /slides
    rss: /pages/atom.xml
  service:
    music:
      endpoint: http://app.atime.me/music-api-server
      provider: netease # or xiami
    zhihu: http://api.kanzhihu.com

# active items for show
meta:
  songlist: 309097660
  zhihu: 616ce531de7f8a1cb33b6ec43ef763fc
  active: 前端
  tags:
    - React
    - 摄影

# chinese localization
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# google analytics
ga:
  id: UA-75024401-1
  url: http://nobackend.website

# disqus setting
disqus:
  disqus_shortname: nobackend-website
  disqus_identifier: nobackend-website
  disqus_url: http://nobackend.website
