permalink: /:year-:month-:day-:title
paginate: 10
markdown: kramdown
encoding: utf-8

author:
  name: 吕立青
  email: jimmy.jinglv@gmail.com
  link: http://blog.jimmylv.info
  weibo: http://weibo.com/liqing215
  github: http://github.com/JimmyLv
  zhihu: http://www.zhihu.com/people/lu-li-qing-90

project:
  title: NoBackend Website
  subtitle: 最美博客
  description: A powerful rich interactive web application by using nobackend tech stack.
  repository: https://github.com/JimmyLv/nobackend.website
  website: http://nobackend.website

# github and api endpoint
posts:
  github:
    user: JimmyLv
    repo: nobackend.website
    folder: _posts
    branch: gh-pages
  api:
    endpoint: http://nobackend.website
    index: http://nobackend.website/api/index.json
    slides: http://nobackend.website/slides
    rss: http://nobackend.website/pages/atom.xml

# active items for show
meta:
  songlist: 309097660
  active: 前端
  tags:
    - React
    - 摄影

# chinese localization
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# google analytics
ga:
  id: UA-75024401-1
  url: http://nobackend.website

# disqus setting
disqus:
  disqus_shortname: nobackend-website
  disqus_identifier: nobackend-website
  disqus_url: http://nobackend.website
