author:
  name: 吕立青
  email: jimmy.jinglv@gmail.com
  link: http://blog.jimmylv.info
  weibo: http://weibo.com/liqing215
  github: http://github.com/JimmyLv
  zhihu: http://www.zhihu.com/people/lu-li-qing-90

project:
  title: NoBackend Website
  description: A powerful rich interactive web application by using nobackend tech stack.
  url: http://nobackend.website

# _posts folder and github repo
posts:
  github:
    user: JimmyLv
    repo: jimmy.lv
    folder: _posts
    branch: gh-pages
  api:
    endpoint: http://blog.jimmylv.info
    index: /api/index.json

# active items
meta:
  songlist: 309097660
  active: 编程
  tags:
    - React
    - 摄影

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# google analytics
ga:
  id: UA-75024401-1
  url: http://nobackend.website

# disqus setting
disqus:
  shortname: nobackend-website
  disqus_identifier: nobackend-website
  disqus_url: http://nobackend.website
